services:
  mariadb:
    image: mariadb:11
    container_name: ${MARIADB_CONTAINER_NAME:-mariadb}
    restart: unless-stopped
    ports:
      - "${PUBLISHED_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    healthcheck:
      test:
        - CMD-SHELL
        - mysqladmin ping -h localhost -uroot -p"$${MARIADB_ROOT_PASSWORD}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${MARIADB_DATA_DIR}:/var/lib/mysql
