# VERSION=1.1.1
services:
  mariadb:
    image: mariadb:11
    container_name: ${MARIADB_CONTAINER_NAME:-mariadb}
    restart: unless-stopped
    ports:
      - "${PUBLISHED_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    healthcheck:
      test:
        - CMD-SHELL
        - mariadb-admin ping --host=127.0.0.1 --user="$$MYSQL_USER" --password="$$MYSQL_PASSWORD" --count=1 --silent --wait=2
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    volumes:
      - ${MARIADB_DATA_DIR}:/var/lib/mysql
