alias: MQTT Leadership Heartbeat
trigger:
  - platform: time_pattern
    seconds: "/30"
action:
  - service: mqtt.publish
    data:
      topic: piha/leader/home-assistant/state
      payload: leader
      retain: true
      qos: 1
  - service: mqtt.publish
    data:
      topic: piha/leader/home-assistant/heartbeat
      payload: >
        {
          "ts": "{{ now().isoformat() }}",
          "host_id": "haos-primary"
        }
      retain: true
      qos: 1
mode: single
