services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: 
    restart: unless-stopped
    ports:
      - ":1883"
    environment:
      - TZ=
    volumes:
      - :/mosquitto/config
      - :/mosquitto/data
      - :/mosquitto/log
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_pub -h localhost -p 1883 -t _healthcheck -m ok -q 0"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
