services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: ${MQTT_CONTAINER_NAME:-mosquitto}
    restart: unless-stopped
    ports:
      - "${PUBLISHED_PORT:-1883}:1883"
    environment:
      - TZ=${TZ:-Europe/Madrid}
    volumes:
      - "${MQTT_CONFIG_DIR:-./config}:/mosquitto/config"
      - "${MQTT_DATA_DIR:-./data}:/mosquitto/data"
      - "${MQTT_LOG_DIR:-./log}:/mosquitto/log"
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_pub -h localhost -p 1883 -t _healthcheck -m ok -q 0"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
