#!/bin/bash
set -e

# Version
VERSION="1.0.2"

BLUE='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

echo -e "${BLUE}PiHA-Deployer NAS Mosquitto bootstrap v${VERSION}${NC}"

is_local_host() {
  case "$NAS_SSH_HOST" in
    localhost|127.0.0.1|::1) return 0 ;;
  esac
  if [ -n "$LOCAL_HOST_ALIAS" ] && [ "$NAS_SSH_HOST" = "$LOCAL_HOST_ALIAS" ]; then
    return 0
  fi
  return 1
}

_load_env_file() {
  local file="$1"
  [ -f "$file" ] || return 0
  while IFS= read -r line; do
    line="$(printf '%s' "$line" | sed $'s/\xEF\xBB\xBF//g; s/\xC2\xA0/ /g' | tr -d '\r')"
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    if [[ $line =~ ^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=(.*)$ ]]; then
      local key="${BASH_REMATCH[1]}"
      local value="${BASH_REMATCH[2]}"
      key="$(echo "$key" | xargs)"
      value="$(echo "$value" | xargs)"
      if [[ $value =~ ^\"(.*)\"$ ]]; then value="${BASH_REMATCH[1]}"; fi
      if [[ $value =~ ^\'(.*)\'$ ]]; then value="${BASH_REMATCH[1]}"; fi
      printf -v "$key" '%s' "$value"
      export "$key"
    fi
  done < "$file"
}

load_env() {
  _load_env_file "${SCRIPT_DIR}/../../common/Common.env"
  _load_env_file "${SCRIPT_DIR}/../../common/common.env"
  _load_env_file "${SCRIPT_DIR}/../common/Common.env"
  _load_env_file "${SCRIPT_DIR}/../common/common.env"
  _load_env_file "${SCRIPT_DIR}/common/Common.env"
  _load_env_file "${SCRIPT_DIR}/common/common.env"
  _load_env_file "$HOME/.piha/common.env"
  _load_env_file "/etc/piha/common.env"

  local bootstrap_env="${SCRIPT_DIR}/.env"
  if [ -f "${SCRIPT_DIR}/.env.bootstrap" ]; then
    bootstrap_env="${SCRIPT_DIR}/.env.bootstrap"
  fi

  if [ ! -f "$bootstrap_env" ]; then
    echo -e "${RED}[ERROR] ${bootstrap_env} not found. Create it based on infrastructure/mqtt/README.md.${NC}"
    exit 1
  fi
  chmod 600 "$bootstrap_env" || true
  _load_env_file "$bootstrap_env"
  echo -e "${GREEN}[OK] Environment loaded${NC}"
}

bool_true() {
  local val
  val="$(printf "%s" "$1" | tr "[:upper:]" "[:lower:]")"
  case "$val" in
    1|y|yes|true|on) return 0 ;;
    *) return 1 ;;
  esac
}

require_vars() {
  local missing=()
  for v in "$@"; do
    if [ -z "${!v}" ]; then
      missing+=("$v")
    fi
  done
  if [ ${#missing[@]} -gt 0 ]; then
    echo -e "${RED}[ERROR] Missing required variables:${NC} ${missing[*]}"
    exit 1
  fi
}

ensure_tools() {
  for tool in ssh scp; do
    if ! command -v "$tool" >/dev/null 2>&1; then
      echo -e "${RED}[ERROR] Required tool '$tool' not found.${NC}"
      exit 1
    fi
  done
}

shell_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\''/g")"
}

remote_exec_cmd() {
  local command="$1"
  if is_local_host; then
    bash -lc "set -e; ${command}"
  else
    ssh -p "$NAS_SSH_PORT" "$NAS_SSH_USER@$NAS_SSH_HOST" "bash -lc $(shell_quote "set -e; ${command}")"
  fi
}

deploy_config_files() {
  local tmp_conf tmp_acl
  tmp_conf=$(mktemp)
  tmp_acl=$(mktemp)

  local allow="false"
  if bool_true "${MQTT_ALLOW_ANONYMOUS:-false}"; then
    allow="true"
  fi

  cat > "$tmp_conf" <<EOF
# Mosquitto configuration managed by PiHA-Deployer
listener 1883
allow_anonymous ${allow}
EOF

  if bool_true "${MQTT_PERSISTENCE:-true}"; then
    cat >> "$tmp_conf" <<'EOF'
persistence true
persistence_location /mosquitto/data/
EOF
  else
    cat >> "$tmp_conf" <<'EOF'
persistence false
EOF
  fi

  cat >> "$tmp_conf" <<'EOF'
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true
EOF

  local acl_created="false"
  if [ -n "$MQTT_USER" ] && [ -n "$MQTT_PASSWORD" ]; then
    cat >> "$tmp_conf" <<'EOF'
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl
EOF

    cat > "$tmp_acl" <<EOF
# ACL generated by PiHA-Deployer
user ${MQTT_USER}
topic readwrite #

# Observers may be granted read access to leadership topics.
# Example:
# user ha-standby
# topic read piha/leader/#
pattern read piha/leader/#
EOF
    acl_created="true"
  fi

  if is_local_host; then
    mkdir -p "$MQTT_CONFIG_DIR" "$MQTT_DATA_DIR" "$MQTT_LOG_DIR"
    cp "$tmp_conf" "${MQTT_CONFIG_DIR}/mosquitto.conf"
    if [ "$acl_created" = "true" ]; then
      cp "$tmp_acl" "${MQTT_CONFIG_DIR}/acl"
    else
      rm -f "${MQTT_CONFIG_DIR}/acl" 2>/dev/null || true
    fi
  else
    remote_exec_cmd "${SUDO}mkdir -p $(shell_quote "$MQTT_CONFIG_DIR") $(shell_quote "$MQTT_DATA_DIR") $(shell_quote "$MQTT_LOG_DIR")"
    scp -P "$NAS_SSH_PORT" "$tmp_conf" "$NAS_SSH_USER@$NAS_SSH_HOST:${MQTT_CONFIG_DIR}/mosquitto.conf" >/dev/null
    if [ "$acl_created" = "true" ]; then
      scp -P "$NAS_SSH_PORT" "$tmp_acl" "$NAS_SSH_USER@$NAS_SSH_HOST:${MQTT_CONFIG_DIR}/acl" >/dev/null
    else
      remote_exec_cmd "${SUDO}rm -f $(shell_quote "${MQTT_CONFIG_DIR}/acl")"
    fi
  fi

  remote_exec_cmd "${SUDO}chmod 640 $(shell_quote "${MQTT_CONFIG_DIR}/mosquitto.conf")"
  if [ "$acl_created" = "true" ]; then
    remote_exec_cmd "${SUDO}chmod 640 $(shell_quote "${MQTT_CONFIG_DIR}/acl")"
  fi

  rm -f "$tmp_conf" "$tmp_acl"
}

setup_auth_files() {
  if [ -n "$MQTT_USER" ] && [ -n "$MQTT_PASSWORD" ]; then
    echo -e "${BLUE}Setting up MQTT authentication...${NC}"
    remote_exec_cmd "${SUDO}docker run --rm -v $(shell_quote "${MQTT_CONFIG_DIR}:/mosquitto/config") eclipse-mosquitto:2.0 sh -c 'touch /mosquitto/config/passwd && mosquitto_passwd -b /mosquitto/config/passwd "$MQTT_USER" "$MQTT_PASSWORD"'"
    remote_exec_cmd "${SUDO}chmod 600 $(shell_quote "${MQTT_CONFIG_DIR}/passwd")"
  else
    echo -e "${YELLOW}[WARN] MQTT_USER/MQTT_PASSWORD not set; broker will allow anonymous connections.${NC}"
  fi
}

main() {
  load_env
  ensure_tools

  NAS_SSH_PORT="${NAS_SSH_PORT:-22}"
  NAS_SSH_USE_SUDO="${NAS_SSH_USE_SUDO:-false}"
  NAS_DEPLOY_DIR="${NAS_DEPLOY_DIR:-/share/Container/compose/mqtt}"
  MQTT_CONFIG_DIR="${MQTT_CONFIG_DIR:-${NAS_DEPLOY_DIR}/config}"
  MQTT_DATA_DIR="${MQTT_DATA_DIR:-${NAS_DEPLOY_DIR}/data}"
  MQTT_LOG_DIR="${MQTT_LOG_DIR:-${NAS_DEPLOY_DIR}/log}"
  PUBLISHED_PORT="${PUBLISHED_PORT:-1883}"

  require_vars NAS_SSH_HOST NAS_SSH_USER NAS_DEPLOY_DIR MQTT_CONFIG_DIR MQTT_DATA_DIR MQTT_LOG_DIR PUBLISHED_PORT

  SUDO=""
  if bool_true "$NAS_SSH_USE_SUDO"; then
    SUDO="sudo "
  fi

  echo -e "${BLUE}Testing NAS access...${NC}"
  if is_local_host; then
    bash -lc "echo ok" >/dev/null 2>&1 || { echo -e "${RED}[ERROR] Unable to execute local shell on NAS.${NC}"; exit 1; }
  else
    if ! ssh -p "$NAS_SSH_PORT" "$NAS_SSH_USER@$NAS_SSH_HOST" "echo ok" >/dev/null 2>&1; then
      echo -e "${RED}[ERROR] SSH connection failed. Verify host, user, and credentials.${NC}"
      exit 1
    fi
  fi
  echo -e "${GREEN}[OK] NAS reachable${NC}"

  echo -e "${BLUE}Preparing directories on NAS...${NC}"
  remote_exec_cmd "${SUDO}mkdir -p $(shell_quote "$NAS_DEPLOY_DIR")"

  local same_dir="false"
  if is_local_host; then
    local script_abs deploy_abs
    script_abs="$(cd "${SCRIPT_DIR}" && pwd)"
    deploy_abs="$(cd "${NAS_DEPLOY_DIR}" && pwd)"
    if [ "$script_abs" = "$deploy_abs" ]; then
      same_dir="true"
    fi
  fi

  echo -e "${BLUE}Checking Docker availability on NAS...${NC}"
  if ! remote_exec_cmd "${SUDO}docker --version >/dev/null 2>&1"; then
    echo -e "${RED}[ERROR] Docker is not available on the NAS. Install Docker before running this script.${NC}"
    exit 1
  fi

  echo -e "${BLUE}Copying docker-compose.yml...${NC}"
  local target="${NAS_DEPLOY_DIR}/docker-compose.yml"
  if is_local_host; then
    if [ "$same_dir" = "true" ] && [ -f "$target" ]; then
      echo -e "${YELLOW}[WARN] docker-compose.yml already present in ${NAS_DEPLOY_DIR}; skipping copy.${NC}"
    else
      if [ -f "${SCRIPT_DIR}/docker-compose.yml" ]; then
        cp "${SCRIPT_DIR}/docker-compose.yml" "$target"
      else
        curl -fsSL https://raw.githubusercontent.com/cdelalama/PiHA-Deployer/main/infrastructure/mqtt/docker-compose.yml -o "$target"
      fi
    fi
  else
    if [ -f "${SCRIPT_DIR}/docker-compose.yml" ]; then
      scp -P "$NAS_SSH_PORT" "${SCRIPT_DIR}/docker-compose.yml" "$NAS_SSH_USER@$NAS_SSH_HOST:${target}" >/dev/null
    else
      curl -fsSL https://raw.githubusercontent.com/cdelalama/PiHA-Deployer/main/infrastructure/mqtt/docker-compose.yml | \\
        ssh -p "$NAS_SSH_PORT" "$NAS_SSH_USER@$NAS_SSH_HOST" "cat > $(shell_quote \"$target\")" >/dev/null
    fi
  fi
  echo -e "${BLUE}Rendering .env for Mosquitto...${NC}"
  local tmp_env
  tmp_env=$(mktemp)
  cat > "$tmp_env" <<EOF
MQTT_CONFIG_DIR=${MQTT_CONFIG_DIR}
MQTT_DATA_DIR=${MQTT_DATA_DIR}
MQTT_LOG_DIR=${MQTT_LOG_DIR}
MQTT_CONTAINER_NAME=${MQTT_CONTAINER_NAME:-mosquitto}
PUBLISHED_PORT=${PUBLISHED_PORT}
TZ=${TZ:-Europe/Madrid}
EOF

  if is_local_host; then
    if [ "$same_dir" = "true" ] && [ -f "${NAS_DEPLOY_DIR}/.env" ] && [ ! -f "${NAS_DEPLOY_DIR}/.env.bootstrap" ]; then
      cp "${NAS_DEPLOY_DIR}/.env" "${NAS_DEPLOY_DIR}/.env.bootstrap"
    fi
    cp "$tmp_env" "${NAS_DEPLOY_DIR}/.env"
  else
    scp -P "$NAS_SSH_PORT" "$tmp_env" "$NAS_SSH_USER@$NAS_SSH_HOST:${NAS_DEPLOY_DIR}/.env" >/dev/null
  fi
  remote_exec_cmd "${SUDO}chmod 600 $(shell_quote "${NAS_DEPLOY_DIR}/.env")"
  rm -f "$tmp_env"

  deploy_config_files
  setup_auth_files

  echo -e "${BLUE}Starting Mosquitto container on NAS...${NC}"
  if remote_exec_cmd "${SUDO}docker compose version >/dev/null 2>&1"; then
    remote_exec_cmd "cd $(shell_quote "$NAS_DEPLOY_DIR") && ${SUDO}docker compose -f docker-compose.yml up -d"
  else
    remote_exec_cmd "cd $(shell_quote "$NAS_DEPLOY_DIR") && ${SUDO}docker-compose -f docker-compose.yml up -d"
  fi

  echo -e "${GREEN}[OK] Mosquitto deployment finished${NC}"
  echo -e "${BLUE}Service details:${NC}"
  echo -e "${BLUE}- Host: ${NAS_SSH_HOST}:${PUBLISHED_PORT}${NC}"
  if [ -n "$MQTT_USER" ]; then
    echo -e "${BLUE}- Auth user: ${MQTT_USER}${NC}"
  else
    echo -e "${YELLOW}[WARN] Anonymous access enabled. Set MQTT_USER/MQTT_PASSWORD to lock down the broker.${NC}"
  fi
  echo -e "${BLUE}- Config: ${MQTT_CONFIG_DIR}${NC}"
  echo -e "${BLUE}- Data: ${MQTT_DATA_DIR}${NC}"
  echo -e "${BLUE}- Log: ${MQTT_LOG_DIR}${NC}"
}

main "$@"

